---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: jayasurya/pipelinetest:v4
          name: pipelinetest
          resources: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  minReadySeconds: 30
  replicas: 4
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: jayasurya/pipelinetest:v4
          name: pipelinetest
          resources: {}
status: {}
